-- Execute isso no SQL Editor do Supabase dashboard

-- 1. Crie a tabela de transações
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description TEXT NOT NULL,
  category TEXT NOT NULL,
  date DATE NOT NULL,
  amount NUMERIC(15,2) NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('receita', 'despesa')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Crie índices para melhorar a performance
CREATE INDEX IF NOT EXISTS idx_transactions_date ON transactions(date);
CREATE INDEX IF NOT EXISTS idx_transactions_type ON transactions(type);
CREATE INDEX IF NOT EXISTS idx_transactions_category ON transactions(category);

-- 3. Configure permissões (Row Level Security)
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;

-- 4. Adicione uma política para permitir acesso de leitura a todos os usuários
CREATE POLICY "Allow select for all users" ON transactions
  FOR SELECT USING (true);
  
-- 5. (Opcional) Adicione alguns dados de exemplo
INSERT INTO transactions (description, category, date, amount, type)
VALUES 
  ('Salário', 'Renda', CURRENT_DATE, 5000.00, 'receita'),
  ('Aluguel', 'Moradia', CURRENT_DATE, 1200.00, 'despesa'),
  ('Supermercado', 'Alimentação', CURRENT_DATE, 550.00, 'despesa'),
  ('Freela', 'Renda Extra', CURRENT_DATE, 1500.00, 'receita'),
  ('Internet', 'Serviços', CURRENT_DATE, 120.00, 'despesa'),
  ('Energia', 'Serviços', CURRENT_DATE, 180.00, 'despesa'); 